/** Sve slike su lokalno u /public/images — bez zavisnosti od Webflow CDN-a */
export const assets = {
  logo: "/images/brand/logo.png",
  logoBw: "/images/brand/logo-bw.png",
  favicon: "/images/brand/favicon.png",
  ogImage: "/images/brand/og.png",
  heroVideo: "/images/hero/video.mp4",
  heroPoster: "/images/hero/poster.jpg",
  homeAbout: "/images/lokacije/pevac.png",
  homeSplitLeft: "/images/saucesce/hero-split.png",
  homeSplitRight: "/images/ostalo/split-right.png",
  shopPevac: "/images/lokacije/pevac.png",
  shopTrg: "/images/lokacije/trg.png",
  shopNovoGroblje: "/images/lokacije/novo-groblje.png",
  kontaktHero: "/images/ostalo/kontakt-hero.png",
  saucesceHero: "/images/saucesce/venac.png",
  product: {
    klasicniBuketi: "/images/buketi/buket-crveno-belo-01.jpeg",
    flowerBox: "/images/buketi/flower-box-only-for-you.jpeg",
    ruze101: "/images/buketi/buket-beli-ruzicnjak.jpeg",
    aranzmanPice: "/images/buketi/aranzman-pice.png",
    saksijsko: "/images/saksijsko/sobne-biljke.jpg",
    saksijskoSobne: "/images/saksijsko/sobne-biljke.jpg",
    saksijskoEksterijer: "/images/saksijsko/biljke-eksterijer.jpg",
    saksijskoPoslovni: "/images/saksijsko/poslovni-prostor.jpg",
    saksijskoSezonske: "/images/saksijsko/sezonske-saksije.jpg",
    ruze: "/images/rezano/crvene-ruze.jpeg",
    lale: "/images/rezano/lale.png",
    ljiljani: "/images/rezano/suncokreti-ljiljani.jpeg",
    egzoticno: "/images/rezano/orhideje.jpeg",
    saucesce: "/images/saucesce/hero-split.png",
  },
  galleryBuketi: [
    "/images/buketi/buket-crveno-belo-01.jpeg",
    "/images/buketi/buket-beli-ruzicnjak.jpeg",
    "/images/buketi/flower-box-only-for-you.jpeg",
    "/images/buketi/buket-ljiljani-roze.jpeg",
    "/images/buketi/buket-suncokreti-01.jpeg",
    "/images/buketi/flower-box-roze.jpeg",
    "/images/buketi/buket-roze-ruze.jpeg",
    "/images/buketi/flower-box-crveni.jpeg",
    "/images/buketi/buket-mesani-suncokret.jpeg",
    "/images/buketi/flower-box-rodjendan.jpeg",
    "/images/buketi/buket-suncokret-crveno.jpeg",
    "/images/buketi/flower-box-crveni-beli.jpeg",
    "/images/buketi/buket-crveno-belo-02.jpeg",
    "/images/buketi/flower-box-roze-kanta.jpeg",
    "/images/buketi/buket-suncokreti-02.jpeg",
    "/images/buketi/buket-crveno-belo-03.jpeg",
  ],
  gallerySaksijsko: [
    "/images/saksijsko/sobne-biljke.jpg",
    "/images/saksijsko/biljke-eksterijer.jpg",
    "/images/saksijsko/poslovni-prostor.jpg",
    "/images/saksijsko/sezonske-saksije.jpg",
    "/images/saksijsko/radnja-enterijer.jpeg",
    "/images/saksijsko/galerija-a.jpg",
    "/images/saksijsko/galerija-b.jpg",
    "/images/saksijsko/galerija-c.png",
  ],
  galleryRezano: [
    "/images/rezano/crvene-ruze.jpeg",
    "/images/rezano/bele-ruze.jpeg",
    "/images/rezano/orhideje.jpeg",
    "/images/rezano/kale-alstromerija.jpeg",
    "/images/rezano/ruze-bicolor.jpeg",
    "/images/rezano/plave-ruze.jpeg",
    "/images/rezano/suncokreti-ljiljani.jpeg",
    "/images/rezano/ruze-mesane.jpeg",
    "/images/rezano/lale.png",
  ],
  gallerySaucesce: ["/images/saucesce/venac.png"],
} as const;
